/**
 * A ballot contains 0 or many BallotEntry objects that form the heart of the
 * live voting system.  Users can add new entries to the ballot, place an
 * unlimited amount of votes and also remove entries from the ballot.
 *
 * Once instantiated the ballot will load all existing entries from the
 * GoInstant system.  Only one instance should exist per page.
 *
 * @param renderer
 *          Function that will be executed in order to render the ballot.  The
 *          function must take exactly one argument, which will be this Ballot
 *          instance.  The function can't be undefined.
 */
function Ballot(renderer)
{
    // Define the URL required to connect to GoInstant.
    var goInstantUrl = "https://goinstant.net/BarelyCool/LiveVote";

    // Instantiate an array data member that is used to hold the ballot entries.
    this.entries = [];

    // Keep a local reference to this class so that it can be used within the
    // callback function below.  Without this reference there will be no way to
    // access class's data members inside the callback.
    var self = this;

    // Create a function private to this constructor that is used to sort the
    // ballot entries.
    var sortEntries = function()
    {
        // Sort the entries now based on the number of votes and, in the
        // case of a tie, alphabetically by name (ascending).
        self.entries = self.entries.sort(function (a, b)
        {
            // Order by votes (descending) and then name (ascending).
            //
            // TODO This needs some work once votes are introduced.
            //
            return a.name > b.name;
        });
    };

    // Attempt to connect to the GoInstant server.
    goinstant.connect(goInstantUrl, function (error, platform, room)
    {
        // Determine if there was an error connecting to the GoInstant server.
        if (error)
        {
            // Something went wrong connecting to the GoInstant server.  Without
            // the connection the app cannot function, so take appropriate
            // action.
            handleError(
                error,
                "Failed to connect to GoInstant.  Application is disabled.");
        }

        // The connection with GoInstant was succesful, so now we can proceed
        // with initializing and configuring the application.
        console.log("Successfully connected to the GoInstant server.");

        // Get the ballot key from the current room.
        self.ballot = room.key("/ballot");

        console.log("Attempting to load ballot entries.");

        // Get the value of the ballet key, which returns a map of the entry
        // identifiers to names.  Note that each id was generated by GoInstant
        // when the entry was added to the ballot.
        self.ballot.get(function(error, entries, context)
        {
            // Check if there was an error retrieving the ballot entries.
            if (error)
            {
                // A error occurred getting the ballot entries.  Without the
                // entries the application is effectively useless, so log the
                // error and disable the application.
                handleError(error, "Failed to load ballot entries.");
            }

            // Proceed only if the entries value that was provided is not
            // undefined.
            if (entries)
            {
                // Get the entry identifiers, which were automatically generated
                // by GoInstant when the entries are added to the ballot.
                var identifiers = Object.keys(entries);

                // For each id get the corresponding entry name.
                for (var i = 0; i < identifiers.length; ++i)
                {
                    // Get the current entry id and name.
                    var id = identifiers[i];
                    var entry = entries[id];
                    
                    // Wrap the entry as a BallotEntry object and add it to the
                    // local array of entries specific to the ballot class.
                    // Prefix the entry id with "/ballot" so that it holds the
                    // GoInstant fully qualified id.
                    self.entries.push(
                        new BallotEntry(
                            entry.name,
                            "/ballot/" + id,
                            entry.votes));
                }

                // Now that all the enties have been loaded we can sort them.
                sortEntries();

                console.log("Successfully loaded ballot entries: "
                    + self.entries);

                // The ballot entries were successfully loaded, so invoke the
                // renderer function in order to render the ballot on the page.
                renderer(self);
            }
            else
            {
                // The entries value that was provided was undefined, which
                // means there aren't any entries yet.
                console.log("There are no ballot entries yet.");
            }
        });
        
        // Define a function responsible for reacting to new entries being added
        // both by the local user and remote users.
        function addEntryListener(entry, context)
        {
            // Wrap the entry as a BallotEntry object and add it to the local
            // data member.  Use the context's "addedKey" property as the id for
            // the ballot.
            self.entries.push(new BallotEntry(entry.name, context.addedKey));

            // Since a new entry was added the array must be sorted again.
            sortEntries();

            // The entries have been updated, so invoke the renderer function in
            // order to render the ballot on the page.
            renderer(self);
        }

        // Register the add entry listener.  This will fire any time anyone adds
        // an entry (both local user and remote users).
        self.ballot.on(
            "add",
            {local:true, bubble:true, listener:addEntryListener});

        // Define a function responsible for reacting to entries being removed
        // both by the local user and remote users.
        function removeEntryListener(entry)
        {
            // Remove the entry from the local data member.
            //self.entries.push(entry);

            // The entries have been updated, so invoke the renderer function in
            // order to render the ballot on the page.
            renderer(self);
        }

        // Register the remove entry listener.  This will fire any time anyone
        // removes an entry (both local user and remote users).
        self.ballot.on(
            "remove",
            {local:true, bubble:true, listener:removeEntryListener});
    });
}

/**
 * Adds a new entry, with the supplied name, to the ballot.
 *
 * @param name
 *          The name of the entry that will be added to the ballot.  Can't be an
 *          empty string.
 */
Ballot.prototype.addEntry = function(name)
{
    console.log("Attempting to add entry '" + name + "' to ballot.");

    // Create a new BallotEntry using the supplied name.  The entry id is not
    // set here because we'll eventually use the id that GoInstant automatically
    // generates when the entry is added to the ballot.  The number of votes
    // for the entry will automatically be set to 0 in the constructor.
    var entry = new BallotEntry(name);

    // Add the new entry to the ballot and listen for any errors.
    this.ballot.add(entry, function(error, context)
    {
        // Check if there was an error adding the entry to the ballot.
        if (error)
        {
            // There was an error adding the entry to the ballot.  Without the
            // ability to add entries the application cannot function, so log
            // the error and disable the application.
            handleError(error, "Failed to add entry '" + name + "' to the "
                + "ballot.");
        }

        console.log("Successfully added entry '" + name + "' to ballot.");
    });
};

/**
 * Removes the entry with the supplied id from the ballot.
 *
 * @param entryId
 *          The id of the entry that will be removed from the ballot.  Can't be
 *          undefined.
 */
Ballot.prototype.removeEntry = function(entryId)
{
    console.log("Attempting to remove entry with id '" + entryId + "' from the "
        + "ballot.");

    // Removes the entry from the ballot and listen for any errors.
    this.ballot.remove("/ballot/" + entryId, function(error)
    {
        // Check if there was an error removing the entry from the ballot.
        if (error)
        {
            // There was an error removing the entry from the ballot.  Without
            // the ability to remove entries the application cannot function, so
            // log the error and disable the application.
            handleError(error, "Failed to remove entry with id '" + entryId
                + "' from the ballot.");
        }

        console.log("Successfully removed entry with id '" + entryId + "' from "
            + "the ballot.");
    });
};